### PR TITLE
This brings basic Outlook 2007 support with toolbar UI.

### PR DESCRIPTION
**Pull request by PierreMarieBaty**
Had to copy/paste the changes by hand using the github.com web interface to avoid cluttering the diff with MSVC's brain-damaged "smart" indentation. Don't laugh. The resulting changes are tiny: 2 files.

### CODE REVIEW

**Comment by aluxnimm** [comment]
Nice work. just needs some rework for memory management. we use comwrappers for the propertyaccessor calls. will look into it.

**Comment by aluxnimm** [comment]
Please check the branch, fixed the issues there and will merge with master

**Comment by PierreMarieBaty** [comment]
Great :)

_outlookMajorVersion could also be used in thisAddIn.cs by making it a global variable, but that's purely cosmetic.

I'm eagerly waiting for the next official version !

**Comment by PierreMarieBaty** [comment]
Actually, there's another cosmetic glitch with the about box. See : http://hpics.li/5ea550d

This is because AboutForm.resx uses newlines (UNIX format, LF). Changing it to Windows format (CR+LF) makes the about box multiline again.

I'm not sure if you actually have this problem, or if it's not a side-effect of Git automatically converting end of lines to UNIX format in source files. But Windows do need CR+LF in forms.

**Pull request merged**
