### PR TITLE
Add Kolab synchronization profile

### PR DESCRIPTION
**Pull request by fjl5**
Kolab (tested with Kolab 16 on Ubuntu 16.04) has solid CalDAV and CardDAV support, so the `Generic CalDAV/CardDAV` profile works quite well. When configuring a bunch of accounts with several (shared) calendards, the configuration gets quite tedious though, especially when you want to map each Kolab calendar to a distinct Outlook folder. This pull request adds a Kolab profile, based on the EasyProject profile. The bulk update in the Kolab profile features:

- Option to auto-create Outlook folders for each Kolab calendar. The new Outlook folder is created in the default folder and named like the Kolab resource with the String ` (Kolab)` appended.
- Option to only create new resources. Resources that have already been configured are identified by their Uri.

Also sets the general option `TriggerSyncAfterSendReceive`: In case of groupware servers like Kolab, users expect all outlook contents to stay in sync. 

In Addition, both `Enter` and `Escape` keys now work in the popup windows. This PR also changes the order of setting `PercentComplete` and `status` in Outlook tasks: Outlook only allows `PercentComplete` values other than `0` when the state indicates that the task is actually worked on. Setting the state first makes sure the `PercentComplete` value does not get lost.

### CODE REVIEW

**Comment by aluxnimm** [comment]
Thank you, we will look into it in the next weeks, rather busy atm.

**Comment by fjl5** [comment]
Sure, thanks for considering it! PS: please feel free to switch to German in case there are issues to discuss.

**Comment by aluxnimm** [comment]
Would you be able to sign a CLA for your contributions? Please contact us via office at caldavsynchronizer.org for details.

**Comment by aluxnimm** [comment]
We are just in the progress of refactoring the whole profiletype stuff so your branch needs restructuring as well.

**Comment by fjl5** [comment]
The new version of the pull request should match the restructured code.

**Comment by aluxnimm** [comment]
Ok we refactored the code a bit and added it to the master already. Please check if everything still works for your use case. Koalb test account would still be useful for us.

**Comment by fjl5** [comment]
Brilliant - will have a look today. The test setup is in the works - should be up in the next few days.

**Comment by fjl5** [comment]
:+1: LGTM - everything works as expected.

**Comment by aluxnimm** [comment]
Ok will be in next release in December.

**Pull request closed without merging**
